/** Home page text (pillar, RECETTE §5). Figures come from the parameter file through `h`. */
import type { FAQ, Helpers } from '../lib/guide-types';
import { CAP_GB, CAP_NI, MAX_REDUNDANCY_GB, MAX_REDUNDANCY_NI, FAMILY_RATE, LEL, P } from '../lib/engine/params';
import { formatMoney, displayDate } from '../lib/format';

const gbp = (x: number, d = 0) => formatMoney(x, d);

export const HOME = {
  title: 'Employment Rights UK 2026/27: Redundancy, Holiday, SMP, SSP',
  description: `Employment rights UK 2026/27 worked out from your real dates: redundancy pay (cap ${gbp(CAP_GB)}), notice, holiday pay, SMP at ${gbp(FAMILY_RATE, 2)} and sick pay at ${gbp(P.ssp.weeklyRate, 2)}, GB and NI.`,
  h1: 'UK employment rights in 2026/27, calculated from your own dates',
  intro: 'Redundancy pay, notice, holiday, maternity, paternity, adoption and sick pay: the statutory minimums for employees in England, Wales, Scotland and Northern Ireland, with every figure read at its official source.',
  resume: `The statutory floor for an employee in the 2026/27 tax year is set by a handful of numbers that changed on 5 and 6 April 2026. A week’s pay used for statutory redundancy pay is capped at ${gbp(CAP_GB)} in Great Britain and ${gbp(CAP_NI)} in Northern Ireland, so the most anyone can receive is ${gbp(MAX_REDUNDANCY_GB)} or ${gbp(MAX_REDUNDANCY_NI)}. Statutory Maternity, Paternity, Adoption and Shared Parental Pay pay ${gbp(FAMILY_RATE, 2)} a week or 90% of average earnings if that is lower, provided earnings reach the lower earnings limit of ${gbp(LEL)} a week. Statutory Sick Pay is ${gbp(P.ssp.weeklyRate, 2)} a week or 80% of earnings, now paid from the first day of sickness with no earnings threshold. Paid holiday stays at 5.6 weeks, capped at ${P.holiday.maxDays} days, and notice runs from one week to twelve. What these headline numbers do not tell you is which date fixes your service, your age and your cap, or how much a day of holiday is worth when your pay varies: the calculators below work that out from the dates on your contract and payslips.`,
  faqs: [
    { q: 'Which redundancy cap applies if I was told before April but leave after 6 April 2026?', a: `The cap that counts is the one in force on the relevant date, normally the day your notice runs out, not the day you were told. Leave on or after 6 April 2026 and a week’s pay is capped at ${gbp(CAP_GB)} in Great Britain (${gbp(CAP_NI)} in Northern Ireland) even if the letter arrived in March. The Increase of Limits Orders say so in their transitional article.` },
    { q: 'Do these calculators work for Northern Ireland?', a: `Yes. Northern Ireland has its own Employment Rights Order and its own figures: a ${gbp(CAP_NI)} redundancy cap, a 26-week qualifying period for paternity leave and none of the 12.07% holiday accrual introduced in Great Britain in 2024. Each calculator asks where you work and applies the right rule; sick pay and family pay rates are the same on both sides.` },
    { q: 'Are the amounts before or after tax?', a: `Before. Statutory payments are shown gross. SMP, SSP, holiday pay and notice pay go through payroll and lose income tax and National Insurance like wages. Redundancy pay is different: the first ${gbp(P.termination.taxFreeThreshold)} of it is not taxed. This site does not work out your take-home pay.` },
    { q: 'My contract promises more than the statutory amount. Which one do I get?', a: 'The better of the two. Statutory rights are a floor: a contract, a staff handbook or a collective agreement can add redundancy pay, notice, holiday or enhanced maternity pay, but cannot take you below the legal minimum. Work out the statutory figure here, then compare it with the clause in your contract.' },
    { q: 'How recent are the figures?', a: `They are the 2026/27 figures, read on ${displayDate(P.retrieved_at, 'en-GB')} in the Increase of Limits Orders, the Social Security Benefits Up-rating Orders and HMRC’s rates and thresholds for employers. The next change is expected in April 2027; until the new rates are published, any week falling after that date is priced at the current rate and flagged.` },
    { q: 'I am a worker, not an employee. Which of these rights do I have?', a: 'Holiday and holiday pay, Statutory Sick Pay and the family payments can apply to workers who are on the payroll and earn enough. Redundancy pay, statutory notice and maternity or paternity leave are for employees only. If you are unsure of your status, GOV.UK’s employment status guide sets out the tests.' },
    { q: 'Is anything I type stored or sent to you?', a: 'No. The calculations run in your browser. Nothing is sent to a server, no account is needed, no cookie is set, and the share link only contains what you typed, in the address bar, for you to send to whoever you choose.' },
  ] as FAQ[],
  body: (h: Helpers) => `
<h2>Why the date matters more than the formula</h2>
<p>Most redundancy calculators ask for your age and your years of service as two whole numbers. That is the half of the job that is easy. The hard half is knowing which day those numbers are measured on. The Employment Rights Act 1996 counts service backwards from the <em>relevant date</em>, which is the day your notice expires, and section 145(5) moves that date later when an employer pays you in lieu instead of letting you work the statutory notice. The extension can turn one year and fifty weeks into two years, which is the difference between nothing and a statutory payment, or push a forty-year-old past the birthday that moves a year of service from one week’s pay to one and a half. ${h.a('redundancy-pay-calculator', 'Our redundancy pay calculator')} starts from the dates themselves: date of birth, first day of continuous employment, the day notice was given and the last day of work. It then shows each year of service with the age you were at its start, so you can check the count against your employer’s letter.</p>
<p>The cap follows a different date. The Increase of Limits Orders apply the new weekly maximum where the relevant date falls on or after 6 April, using the date as defined without the section 145(5) extension. Someone whose notice ends on 5 April 2026 is capped at the old figure; a colleague leaving the next day gets the new one. ${h.a('redundancy-relevant-date', 'The relevant date, explained with examples')} walks through the common cases: notice worked, notice paid in lieu, notice longer than the statutory minimum, and a dismissal without notice for redundancy.</p>

<h2>Holiday pay is a calculation, not a number of days</h2>
<p>Holiday entitlement is the part of employment law people think they understand: 5.6 weeks, or 28 days for a five-day week. The questions that reach Acas are about money. A week’s holiday pay for anyone whose pay varies is an average over the last 52 weeks in which they were paid, looking back up to 104 weeks to find them, and it must include regular overtime, commission and seniority payments for at least the first four weeks of leave. ${h.a('holiday-pay-calculator', 'The holiday pay calculator')} does that average and prices the remaining 1.6 weeks at the basic rate where the law allows it. ${h.a('irregular-hours-holiday-calculator', 'Irregular-hours and part-year workers in Great Britain')} build up leave at 12.07% of hours worked in each pay period and can be paid rolled-up holiday pay instead, a 12.07% uplift shown on each payslip; neither rule exists in Northern Ireland, where 5.6 weeks a year remains the measure.</p>
<p>Leaving a job turns untaken holiday into money. Regulation 14 of the Working Time Regulations gives the formula, (A × B) − C: the year’s entitlement times the share of the leave year worked, minus what was taken. ${h.a('holiday-pay-when-leaving', 'Holiday pay when leaving')} applies it with your own leave year, and ${h.a('bank-holidays-and-annual-leave', 'the bank holiday tool')} lists the 2026 and 2027 bank holidays for England and Wales, Scotland (including the World Cup bank holiday of 15 June 2026) and Northern Ireland, with the pro-rata share a part-timer is owed when bank holidays are given on top of the statutory minimum.</p>

<h2>Family pay week by week</h2>
<p>Statutory Maternity Pay is two different payments stitched together: six weeks at 90% of average weekly earnings, then thirty-three weeks at the flat rate or 90% if lower. The flat rate rises every April, and the new rate starts with the first pay week that begins on or after the first Sunday of April, which is how HMRC’s own calculator applies it. For a baby due in the spring the 39 weeks straddle that change. ${h.a('maternity-pay-calculator', 'The maternity pay calculator')} lays out every week with its date and amount, flags the qualifying week, the earliest start of leave and the deadline to tell your employer, and says plainly when a week falls after April 2027, whose rate has not been set yet. ${h.a('maternity-leave-dates-calculator', 'The maternity leave dates calculator')} gives the calendar on its own.</p>
<p>Paternity leave changed on 6 April 2026 in Great Britain: it no longer needs 26 weeks of service, and the two weeks can be taken separately at any point in the first year. Paternity pay still needs the 26 weeks and average earnings at the lower earnings limit. Northern Ireland kept the earlier rules, a qualifying period and a single block within 56 days of the birth. ${h.a('paternity-pay-calculator', 'The paternity pay calculator')} asks where you work. ${h.a('shared-parental-pay-calculator', 'Shared parental pay')} converts unused maternity or adoption leave and pay into weeks that either parent can take, and ${h.a('adoption-pay-calculator', 'adoption pay')} works from the matching week instead of the due date.</p>

<h2>Sick pay from day one</h2>
<p>The biggest change of the year is the one fewest people have noticed. Since 6 April 2026 Statutory Sick Pay is paid from the first day of sickness rather than the fourth, and the lower earnings limit that used to exclude low earners has gone. In exchange, the payment is capped at 80% of normal weekly earnings when that is less than ${h.gbp(P.ssp.weeklyRate, 2)}. For anyone earning more than about ${h.gbp(P.ssp.weeklyRate / P.ssp.earningsShare)} a week nothing changes in the weekly rate; for part-timers on small hours, a three-day absence that used to pay nothing now pays something. ${h.a('statutory-sick-pay-calculator', 'The sick pay calculator')} uses HMRC’s daily-rate method, splits the payment by pay week and counts what is left of the 28 weeks when spells link together. ${h.a('ssp-changes-april-2026', 'What changed in April 2026')} compares the old and the new rules on real cases.</p>

<h2>What this site does not do</h2>
<p>It does not work out income tax or National Insurance, and it does not decide whether a dismissal was fair. It applies the statutory minimums to the facts you enter; your contract may promise more, and only an employment tribunal can decide a dispute. Where a rule depends on a fact we cannot see, the calculator asks for it or says so. Each page lists its official sources, and the ${h.a('method', 'method page')} explains how each result is computed and tested against the rules of the GOV.UK calculators. For advice on your own case, Acas in Great Britain and the Labour Relations Agency in Northern Ireland are free.</p>
`,
};
